blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:pk>', views.blog_post, name="blog_post")
]

landing_page/urls.py
from django.urls import path
from landing_page import views


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('cv/', views.cv, name='cv')
]

magic_of_programming/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('landing_page.urls')),
    path('blog/', include('blog.urls'))
]

projects/urls.py
from projects import views
from django.urls import path

app_name = "projects"

urlpatterns = [
    path('', views.projects_list, name="projects"),
    path('<int:pk>', views.project_details, name="project_details")
]

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField()
    last_modified = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} - {self.body[0:50]}...'

landing_page/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor.fields import RichTextField
from solo.models import SingletonModel
# Create your models here.


class Work(models.Model):
    job_title = models.CharField(max_length=120)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    present = models.BooleanField()
    company = models.CharField(max_length=120)
    short_description = models.CharField(max_length=150)
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.job_title

    class Meta:
        ordering = ['start_date']
        verbose_name = "Work Experience"
        verbose_name_plural = "Work Experience"


class Education(models.Model):
    field_of_study = models.CharField(max_length=120)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    present = models.BooleanField()
    institution = models.CharField(max_length=120)
    short_description = models.CharField(max_length=150)
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.field_of_study

    class Meta:
        ordering = ['start_date']
        verbose_name = "Education"
        verbose_name_plural = "Education"


class Skill(models.Model):
    name = models.CharField(max_length=120)
    percentage = models.IntegerField(
        default=60,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ]
     )
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class SiteConfiguration(SingletonModel):
    name = models.CharField(max_length=120)
    phone = PhoneNumberField(null=False, blank=False, unique=True)
    email = models.EmailField(max_length=254)
    welcome_message = models.CharField(max_length=255)
    hobbies_text = RichTextField()
    avatar_url = models.URLField(default="http://placekitten.com/g/200/300")
    created_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Site Configuration"
        verbose_name_plural = "Site Configuration"

projects/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Tool(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Categories"


class Image(models.Model):
    url = models.URLField()
    alt_text = models.CharField(max_length=50)

    def __str__(self):
        return self.alt_text

    class Meta:
        ordering = ['alt_text']


class Project(models.Model):
    title = models.CharField(max_length=70)
    categories = models.ManyToManyField(Category)
    tools = models.ManyToManyField(Tool)
    short_description = models.CharField(max_length=150)
    description = RichTextField()
    source_url = models.CharField(max_length=250, null=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    image = models.OneToOneField(
        Image,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['created']

landing_page/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=255)
    sender = forms.CharField(max_length=150)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
# Create your views here.


def blog(request):
    posts = Post.objects.all()
    return render(request, 'blog/blog.html', {"posts": posts})


def blog_post(request, pk):
    post = Post.objects.get(pk=pk)
    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
    }

    return render(request, "blog/post.html", context)

landing_page/views.py
from landing_page.models import Work, Education, Skill, SiteConfiguration
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

# Create your views here.


def home(request):
    web_info = SiteConfiguration.objects.latest('created_on')
    return render(request, 'landing_page/home.html', {
        'web_info': web_info
    })


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            title = "Website Inquiry"
        body = {
            'subject': form.cleaned_data['subject'],
            'sender': form.cleaned_data['sender'],
            'email': form.cleaned_data['email_address'],
            'message': form.cleaned_data['message'],
        }
        message = "\n".join(body.values())

        try:
            send_mail(title, message, 'admin@example.com', ['admin@example.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return redirect('home')

    form = ContactForm()
    return render(request, 'landing_page/contact.html', {'form': form})


def cv(request):
    works = Work.objects.all()
    educations = Education.objects.all()
    web_info = SiteConfiguration.get_solo()
    skills = Skill.objects.all()
    return render(request, 'landing_page/cv.html', {
        'works': works,
        'educations': educations,
        'skills': skills,
        'web_info': web_info
    })

projects/views.py
from django.shortcuts import render
from projects.models import Project


# Create your views here.
def projects_list(request):
    projects = Project.objects.all()
    return render(request, 'projects/projects.html', {'projects': projects})


def project_details(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/project.html', {'project': project})

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="page lanidng-page">
        <section class="portfolio-block block-intro">
            <div class="container">
                <div class="row">
                    <h1>Magic of Programming Blog</h1>
                </div>
            </div>
        </section>

{#    <header class="masthead" style="background-image:url({% static 'assets/img/nature/image1.jpg' %});">#}
{#        <div class="overlay"></div>#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-md-10 col-lg-8 mx-auto">#}
{#                    <div class="site-heading">#}
{#                        <h1>Clean Blog</h1><span class="subheading">A Blog Theme by Start Bootstrap</span></div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </header>#}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8">
            {% for post in posts %}
            <div class="post-preview">
                    <a href="{% url 'blog:blog_post' post.pk %}">
                        <h2 class="post-title">{{ post.title }}</h2>
                    </a>
                    <p>{{ post.body|truncatechars:255|safe }}</p>
                </div>
                <hr>
            {% endfor %}

            </div>
        </div>
    </div>
    </main>
{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}

{% block content %}
    <main class="page">
     <article>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto">
                    <div class="heading">
                        <h1 class="blog-title">{{ post.title }}</h1>
                        <small>Created on: {{ post.created_on }}</small><br>
                        {% for category in post.categories.all %}
                            <span class="category">{{ category.name }}</span>
                        {% endfor %}
                    </div>

                    <br>
                    {{ post.body|safe }}
                </div>
            </div>
        </div>
    </article>
    </main>


{% endblock %}

landing_page/templates/landing_page/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main class="page hire-me-page">
        <section class="portfolio-block hire-me">
            <div class="container">
                <div class="heading">
                    <h2>Hire Me</h2>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Hire Me</button>
                </form>
            </div>
        </section>
    </main>
{% endblock %}

landing_page/templates/landing_page/cv.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main class="page cv-page">
        <section class="portfolio-block block-intro border-bottom">
            <div class="container">
                <div class="avatar" style="background-image:url({{ web_info.avatar_url }});"></div>
                <div class="about-me">
                    <p>{{ web_info.welcome_message }}</p><a class="btn btn-outline-primary" role="button" href="#">Hire me</a></div>
            </div>
        </section>
        <section class="portfolio-block cv">
            <div class="container">
                <div class="work-experience group">
                    <div class="heading">
                        <h2 class="text-center">Work Experience</h2>
                    </div>
                    {% for work in works %}
                        {% if work.display %}
                            <div class="item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h3>{{ work.job_title }}</h3>
                                        <h4 class="organization">{{ work.company }}</h4>
                                    </div>
                                    <div class="col-md-6"><span class="period">{{ work.start_date }} - {{ work.end_date }}</span></div>
                                </div>
                                <p class="text-muted">{{ work.short_description }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}

                <div class="education group">
                    <div class="heading">
                        <h2 class="text-center">Education</h2>
                    </div>
                    {% for education_item in educations %}
                        {% if education_item.display %}
                            <div class="item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h3>{{ education_item.field_of_study }}</h3>
                                        <h4 class="organization">{{ education_item.institution }}</h4>
                                    </div>
                                    <div class="col-6"><span class="period">{{ education_item.start_date }} - {{ education_item.end_date }}</span></div>
                                </div>
                                <p class="text-muted">{{ education_item.short_description }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                <div class="group">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="skills portfolio-info-card">
                                <h2>Skills</h2>

                                {% for skill in skills %}
                                    {% if skill.display %}
                                        <h3>{{ skill.name }}</h3>
                                        <div class="progress">
                                            <div class="progress-bar" aria-valuenow="{{ skill.percentage }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ skill.percentage }}%;"><span class="sr-only">{{ skill.percentage }}%</span></div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="contact-info portfolio-info-card">
                                <h2>Contact Info</h2>
                                <div class="row">
                                    <div class="col-1"><i class="icon ion-person icon"></i></div>
                                    <div class="col-9"><span>{{ web_info.name }}</span></div>
                                </div>
                                <div class="row">
                                    <div class="col-1"><i class="icon ion-ios-telephone icon"></i></div>
                                    <div class="col-9"><span>{{ web_info.phone }}</span></div>
                                </div>
                                <div class="row">
                                    <div class="col-1"><i class="icon ion-at icon"></i></div>
                                    <div class="col-9"><span>{{ web_info.email }}</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="hobbies group">
                    <div class="heading">
                        <h2 class="text-center">Hobbies</h2>
                    </div>
                    <p class="text-center text-muted">{{ web_info.hobbies_text|safe }}</p>
                </div>
            </div>
        </section>
    </main>
   {% endblock %}

landing_page/templates/landing_page/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="page lanidng-page">
        <section class="portfolio-block block-intro">
            <div class="container">
                <div class="avatar" style="background-image:url({{ web_info.avatar_url }});"></div>
                <div class="about-me">
                    <p>{{ web_info.welcome_message }}</p><a
                        class="btn btn-outline-primary" role="button" href="#">Hire me</a></div>
            </div>
        </section>
        <section class="portfolio-block photography">
            <div class="container">
                <div class="row no-gutters">
                    <div class="col-md-6 col-lg-4 item zoom-on-hover"><a href="#">
                        <img class="img-fluid image" src="{% static 'assets/img/nature/image5.jpg' %}"></a>
                    </div>
                    <div class="col-md-6 col-lg-4 item zoom-on-hover"><a href="#">
                        <img class="img-fluid image" src="{% static 'assets/img/nature/image2.jpg' %}"></a>
                    </div>
                    <div class="col-md-6 col-lg-4 item zoom-on-hover">
                        <a href="#"><img class="img-fluid image" src="{% static 'assets/img/tech/image4.jpg' %}"></a>
                    </div>
                </div>
            </div>
        </section>
        <section class="portfolio-block call-to-action border-bottom">
            <div class="container">
                <div class="d-flex justify-content-center align-items-center content">
                    <h3>Like what you see?</h3>
                    <button class="btn btn-outline-primary btn-lg" type="button">Hire me</button>
                </div>
            </div>
        </section>
        <section class="portfolio-block skills">
            <div class="container">
                <div class="heading">
                    <h2>Special Skills</h2>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card special-skill-item border-0">
                            <div class="card-header bg-transparent border-0"><i class="icon ion-ios-star-outline"></i>
                            </div>
                            <div class="card-body">
                                <h3 class="card-title">Web Design</h3>
                                <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo
                                    odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida
                                    at eget metus.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card special-skill-item border-0">
                            <div class="card-header bg-transparent border-0"><i
                                    class="icon ion-ios-lightbulb-outline"></i></div>
                            <div class="card-body">
                                <h3 class="card-title">Interface Design</h3>
                                <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo
                                    odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida
                                    at eget metus.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card special-skill-item border-0">
                            <div class="card-header bg-transparent border-0"><i class="icon ion-ios-gear-outline"></i>
                            </div>
                            <div class="card-body">
                                <h3 class="card-title">Photography and Print</h3>
                                <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo
                                    odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida
                                    at eget metus.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

projects/templates/projects/project.html
{% extends 'base.html' %}


{% block content %}
    <main class="page project-page">
        <section class="portfolio-block project">
            <div class="container">
                <div class="heading">
                    <h2>{{ project.title }}</h2>
                </div>
                <div class="image" style="background-image:url({{ project.image.url }});"></div>
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-1 info">
                        <h3>Description</h3>
                        <p>{{ project.description }}</p>
                    </div>
                    <div class="col-12 col-md-3 offset-md-1 meta">
                        <div class="tags">
                            <span class="meta-heading">Tools and technologies</span>
                            {% for tool in project.tools.all %}
                                <p>{{ tool }}</p>
                            {% endfor %}
                            <span class="meta-heading">Date</span>
                            <span>25-04-2017</span></div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

projects/templates/projects/projects.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <main class="page projects-page">
        <section class="portfolio-block projects-cards">
            <div class="container">
                <div class="heading">
                    <h2>Recent Work</h2>
                </div>
                <div class="row">
                {% for project in projects.all %}

                    <div class="col-md-6 col-lg-4">
                        <div class="card border-0"><a href="{% url 'projects:project_details' project.pk %}">
                            <img class="card-img-top scale-on-hover" src="{{ project.image.url }}" alt="{{ project.image.alt_text }}">
                        </a>
                            <div class="card-body">
                                <h6><a href=" {% url 'projects:project_details' project.pk %}">{{ project.title }}</a></h6>
                                <p class="text-muted card-text">{{ project.short_description }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/base.css' %}">
</head>
<body>
    <div class="content">
            <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">
        <div class="container">
            <a class="navbar-brand logo" href="#">Alex Ines</a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse"
                id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'projects:projects' %}">Portfolio</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'cv' %}">CV</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:blog' %}">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    </div>

   <script src="{% static 'assets/js/jquery.min.js' %}"></script>
   <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
   <script src="{% static 'assets/js/theme.js' %}"></script>

</body>
</html>